### ISSUE TITLE
Project view doesn't update after sync

### ISSUE THREAD

**Issue by richard-edwards** [budowski/budoist#1]
Steps to reproduce:
1. Go into any project
2. Using the todoist web interface, add an item to that project
3. Either wait for an auto sync or perform a manual sync in budoist
4. Project view doesn't change
5. Go back to list of projects and back to same project and the list is now up to date

Thanks for providing this. I just saw this from a twitter post by @todoist today and I was almost to the point of starting to create my own android app. If you need help testing at all let me know, I'm using a Xoom tablet and would be happy to help out.

**Comment by budowski** [comment]
Thanks for your feedback!
Please download the latest version (1.0.8) which has this issue fixed (at least when you press the "Sync now" button).

**Comment by richard-edwards** [comment]
Thanks for the update. Is there any chance you can get the regular timed sync to update the project view as well? I'll explain how I'm using this and maybe that will help.

I have a Xoom in the dock with Budoist set as the dock application, so whenever I put it into the dock Budoist cranks up, goes to my default project. Awesome!

Now, while at my desktop I have a couple of Slickrun commands (td and tm). td adds an item to my current day (the default view I'm looking at in Budoist) and tm puts it in tomorrow's list. Having to resync from the tablet each time I put a new item in the today list is a pain. Essentially I'm using the tablet as a little todo window sitting in my desk. It's always on and open and doesn't interfere with my other monitors. Then when I'm done work or leave the office, I take it away and have my current list with me always.

Thanks for your help on this.

**Comment by budowski** [comment]
I see.. Alright, I'll work on it (I assume I'll have some time to work on
it during this weekend).

On Wed, Mar 21, 2012 at 1:56 PM, redwards1966 <
reply@reply.github.com

**Comment by richard-edwards** [comment]
Great, thanks. I was thinking about forking the project and looking into it
as well. Would you consider a pull request if I figured it out? At the time
I found your project I was already psyched about doing my own Todoist app
for Android but then I saw yours and it did most of what I needed already.

On Wed, Mar 21, 2012 at 4:00 PM, budowski <
reply@reply.github.com

> wrote:
> 
> I see.. Alright, I'll work on it (I assume I'll have some time to work on
> it during this weekend).
> 
> On Wed, Mar 21, 2012 at 1:56 PM, redwards1966 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Thanks for the update. Is there any chance you can get the regular timed
> > sync to update the project view as well? I'll explain how I'm using this
> > and maybe that will help.
> > 
> > I have a Xoom in the dock with Budoist set as the dock application, so
> > whenever I put it into the dock Budoist cranks up, goes to my default
> > project. Awesome!
> > 
> > Now, while at my desktop I have a couple of Slickrun commands (td and
> > tm).
> > td adds an item to my current day (the default view I'm looking at in
> > Budoist) and tm puts it in tomorrow's list. Having to resync from the
> > tablet each time I put a new item in the today list is a pain.
> > Essentially
> > I'm using the tablet as a little todo window sitting in my desk. It's
> > always on and open and doesn't interfere with my other monitors. Then
> > when
> > I'm done work or leave the office, I take it away and have my current
> > list
> > with me always.
> > 
> > Thanks for your help on this.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/budowski/budoist/issues/1#issuecomment-4615756
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/budowski/budoist/issues/1#issuecomment-4625831

## 

Regards,

Richard

**Comment by budowski** [comment]
No problem. Sure thing, tell me when you're ready for it..

On Wed, Mar 21, 2012 at 10:03 PM, redwards1966 <
reply@reply.github.com

**Comment by budowski** [comment]
Hey,

I've updated the source code + binary in the Android market (also fixed some other bugs).

**Comment by richard-edwards** [comment]
Thanks for the update. I tested it out on the Xoom and it works great now.

On Thu, Mar 22, 2012 at 8:03 PM, budowski <
reply@reply.github.com

> wrote:
> 
> Hey,
> 
> I've updated the source code + binary in the Android market (also fixed
> some other bugs).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/budowski/budoist/issues/1#issuecomment-4651128

## 

Regards,

Richard
