### ISSUE TITLE
Sync failure

### ISSUE THREAD

**Issue by dalb8** [budowski/budoist#11]
The sync starts and the progress bar moves, but always an error. It works on another phone . Built from source.

 --------- beginning of /dev/log/system
W/InputManagerService( 1663): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@409cbda0
--------- beginning of /dev/log/main
D/dalvikvm( 1775): GC_EXPLICIT freed 7K, 56% free 3531K/7943K, external 1866K/2536K, paused 38ms
D/dalvikvm( 1775): GC_EXPLICIT freed <1K, 56% free 3531K/7943K, external 1866K/2536K, paused 35ms
D/dalvikvm( 1663): GC_EXTERNAL_ALLOC freed 688K, 39% free 8925K/14599K, external 4011K/4033K, paused 75ms
I/ActivityManager( 1663): Starting: Intent { act=android.intent.action.MAIN flg=0x10100000 cmp=budo.budoist/.Bootloader } from pid 1663
W/KeyCharacterMap( 1775): Can't open keycharmap file
W/KeyCharacterMap( 1775): Error loading keycharmap file '/system/usr/keychars/nvodm_touch.kcm.bin'. hw.keyboards.65542.devname='nvodm_touch'
W/KeyCharacterMap( 1775): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
W/KeyCharacterMap(13952): Can't open keycharmap file
W/KeyCharacterMap(13952): Error loading keycharmap file '/system/usr/keychars/nvodm_touch.kcm.bin'. hw.keyboards.65542.devname='nvodm_touch'
W/KeyCharacterMap(13952): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
D/JsonServer(13952): Executing GET request url = https://todoist.com/API/login?password=merrymonth&email=dyjjgdfgj%40hjhgf.com
D/dalvikvm(13952): GC_CONCURRENT freed 598K, 49% free 3387K/6535K, external 880K/1035K, paused 3ms+1ms
D/JsonServer(13952): Result data: {"gmail_domain": null, "notifo": null, "start_page": "_info_page", "last_used_ip": "50.18.181.105", "twitter": null, "is_premium": false, "sort_order": 0, "full_name": "davr", "api_token": "195b243d0fdf8e6093d9149e85ecdd56794fa101", "timezone": "Europe\/Dublin", "jabber": null, "id": 379829, "tz_offset": ["+01:00", 1, 0, 1], "msn": null, "email": "fgjgdgj@fhjgfnj", "start_day": 1, "time_format": 0, "mobile_number": null, "mobile_host": null, "date_format": 0, "premium_until": null, "join_date": "Sat 22 Sep 2012 14:21:22 +0000", "default_reminder": null}
D/JsonServer(13952): Executing GET request url = http://todoist.com/API/getProjects?token=195b243d0fdf8e6093d9149e85ecdd56794fa101 
W/InputManagerService( 1663): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@40a2e8a0
D/JsonServer(13952): Result data: [{"last_updated": "1348488202.21", "name": "proj", "user_id": 379829, "color": "#bde876", "collapsed": 0, "archived_date": null, "item_order": 1, "indent": 1, "is_archived": 0, "archived_timestamp": 0, "cache_count": 1, "id": 99964614}]
E/Budoist (13952): SyncResult: DO_NOTHING; Local item: <Project: 99964614 (owner user: 0); dirty: UNMODIFIED; name: 'proj'; itemCount: 2; colorIndex: 0; indent: 1; itemOrder: 1>; Remote item: <Project: 99964614 (owner user: 379829); dirty: UNMODIFIED; name: 'proj'; itemCount: 1; colorIndex: 0; indent: 1; itemOrder: 1>;
D/JsonServer(13952): Executing GET request url = http://todoist.com/API/getLabels?token=195b243d0fdf8e6093d9149e85ecdd56794fa101 
D/dalvikvm(13952): GC_CONCURRENT freed 132K, 43% free 3768K/6535K, external 848K/1035K, paused 4ms+2ms
D/JsonServer(13952): Result data: {"green": {"color": 0, "count": 0, "uid": 379829, "id": 268407, "name": "green"}, "fgjl": {"color": 0, "count": 0, "uid": 379829, "id": 268406, "name": "fgjl"}}
E/Budoist (13952): SyncResult: DO_NOTHING; Local item: <Label: 268407 (owner user: 0); name: 'green'; colorIndex: 0; count: 1>; Remote item: <Label: 268407 (owner user: 379829); name: 'green'; colorIndex: 0; count: 0>;
E/Budoist (13952): SyncResult: DO_NOTHING; Local item: <Label: 268406 (owner user: 0); name: 'fgjl'; colorIndex: 0; count: 1>; Remote item: <Label: 268406 (owner user: 379829); name: 'fgjl'; colorIndex: 0; count: 0>;
D/JsonServer(13952): Executing GET request url = http://todoist.com/API/getCompletedItems?token=195b243d0fdf8e6093d9149e85ecdd56794fa101&project_id=99964614 
D/JsonServer(13952): Result data: []
D/JsonServer(13952): Executing GET request url = http://todoist.com/API/getUncompletedItems?token=195b243d0fdf8e6093d9149e85ecdd56794fa101&project_id=99964614 
D/JsonServer(13952): Result data: [{"due_date": "Tue 25 Sep 2012 23:59:59", "collapsed": 0, "labels": [], "is_dst": 1, "has_notifications": 0, "checked": 0, "indent": 3, "children": null, "content": "dgjk", "user_id": 379829, "mm_offset": 60, "in_history": 0, "id": 100798884, "priority": 1, "item_order": 2, "project_id": 99964614, "is_archived": 0, "date_string": "25 Sep 2012"}]
E/Budoist (13952): SyncResult: DO_NOTHING; Local item: <Item: 100798884 (owner user: 0; project: 99964614); content: 'dgjk'; completed: false; indent: 3; itemOrder: 2; priority: 1; label ids: []; due date: Tue Sep 25 23:59:59 GMT+01:00 2012 (1348613999000); date string: 25 Sep 2012; note count: 0; dirtyState: UNMODIFIED>; Remote item: <Item: 100798884 (owner user: 379829; project: 99964614); content: 'dgjk'; completed: false; indent: 3; itemOrder: 2; priority: 1; label ids: []; due date: Tue Sep 25 23:59:59 GMT+01:00 2012 (1348613999000); date string: 25 Sep 2012; note count: 0; dirtyState: UNMODIFIED>;
D/JsonServer(13952): Executing GET request url = http://todoist.com/API/addItem?content=ghj&id=5825430&item_order=2&indent=1&token=195b243d0fdf8e6093d9149e85ecdd56794fa101&priority=1&project_id=51217419 
D/dalvikvm(13952): GC_FOR_MALLOC freed 547K, 45% free 3857K/6919K, external 848K/1035K, paused 50ms
D/dalvikvm(13952): GC_CONCURRENT freed 1K, 43% free 3953K/6919K, external 848K/1035K, paused 3ms+2ms
D/JsonServer(13952): Result data: "ERROR_PROJECT_NOT_FOUND"
E/Budoist (13952): Sync Exception: budo.budoist.services.TodoistServerException
E/Budoist (13952): Sync Exception: null
E/Budoist (13952): budo.budoist.services.TodoistServer: parseReturnValue: 834
E/Budoist (13952): budo.budoist.services.TodoistServer: addItem: 495
E/Budoist (13952): budo.budoist.services.TodoistClient: syncAddLocalToRemote: 1447
E/Budoist (13952): budo.budoist.services.TodoistClient: handleSyncResult: 1166
E/Budoist (13952): budo.budoist.services.TodoistClient: syncLists: 1147
E/Budoist (13952): budo.budoist.services.TodoistClient: syncItems: 1032
E/Budoist (13952): budo.budoist.services.TodoistClient: syncAll: 852
E/Budoist (13952): budo.budoist.views.LoginView$1: run: 271
E/Budoist (13952): java.lang.Thread: run: 1019
W/InputManagerService( 1663): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4096da48
D/dalvikvm( 1663): GC_EXTERNAL_ALLOC freed 222K, 40% free 8865K/14599K, external 3688K/3712K, paused 79ms
D/dalvikvm( 1663): GC_EXTERNAL_ALLOC freed 26K, 40% free 8852K/14599K, external 3053K/3071K, paused 75ms
I/InputDispatcher( 1663): Dropped event because of pending overdue app switch.
I/ActivityManager( 1663): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 cmp=org.jtb.alogcat/.LogActivity } from pid 1663
W/InputManagerService( 1663): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@40a29948 (uid=10310 pid=13952)
D/dalvikvm( 1775): GC_EXPLICIT freed 1K, 56% free 3532K/7943K, external 1866K/2536K, paused 25ms

**Comment by budowski** [comment]
It seems like during the sync process, it's trying to add a new task to a non-existent project. This usually means the project was deleted (from the website, not the app).
I'll try and see if I can implement a nicer way of handling this kind of situation...

**Comment by budowski** [comment]
Added cleaner handling and recovery in version 1.2.9

**Comment by dalb8** [comment]
Thanks. But f-droid can't update this until the source code is published. If we dont find the source code after discovering a new version it could get put to one side for a long while. If you could tag your releases on Github that would solve the problem.

**Comment by budowski** [comment]
OK, done - now it's tagged as "v1.2.9"

**Comment by dalb8** [comment]
Thanks. Sorry, I didnt realize you bumped the version with the last commit. I should have read whole description. It is better to give version bump its own commit though.
