### ISSUE TITLE
Queries working wrong

### ISSUE THREAD

**Issue by michicoder** [budowski/budoist#3]
Hi! I've noticed that there are problems with the queries. Today, i.e., I have a task with due data yesterday and is not showed (with the query "Overdue", nor "Yesterday", etc).

If I query the API I get the task correctly... Any ideas?

I put the json response, maybe it helps

[{"data": [{"due_date": "Mon May 28 23:59:59 2012", "collapsed": 0, "labels": [], "is_dst": 1, "has_notifications": 0, "checked": 0, "indent": 1, "children": "", "content": "This is my task description", "user_id": 154052, "mm_offset": 120, "in_history": 0, "id": 9287710, "priority": 1, "item_order": 27, "project_id": 816241, "chains": null, "date_string": "28. May 2012"}], "type": "overdue"}]

**Comment by budowski** [comment]
Hmm.. It seems like your date string ("28. May 2012") is invalid since it has a dot right after the day.
However, after further checking, it seems like Todoist website accepts this kind of format as well - I will update Budoist to accept it as well.
