### ISSUE TITLE
Enhancement : save projects display

### ISSUE THREAD

**Issue by benblan** [budowski/budoist#4]
It would be nice if budoist could save the project tree state.
Today, if I go to the 'Projects'  tab, all projects are expanded. If I have many projects, I like to collapse some them while keeping others expanded.
If I change tab ( for example 'Queries') and then go back to the 'Projects tab', all projects are expanded again, the former state is lost.

**Comment by budowski** [comment]
Fixed it in version 1.2.2.
Projects tree state will only be refreshed when one of the following events occur:
- Project is deleted
- Project is added/updated
- Sync is completed
