### ISSUE TITLE
Enhacement: "No Date" query

### ISSUE THREAD

**Issue by txeni** [budowski/budoist#5]
Hi,

First thanks for your work and congrats because I think yours is the best todoist client for android:)
One thing I would love you to add if possible is the query "no date" to get the tasks without a due date, the same way you can do in the web app.
It's an interesting thing because in the web app is working but it's not listed in the "Query Syntax" info.
I create a lot of tasks with no due date because I want them to appear constantly in my queries until I finish them.
In any case I think is a useful addition.

Thanks,
Carlos

**Comment by budowski** [comment]
Added support in version 1.2.3

**Comment by txeni** [comment]
Thanks so much!
Carlos

**Comment by budowski** [comment]
No problem :-)

Thanks for using Budoist!
