### ISSUE TITLE
plz, provide an .apk for those, that do not have google play market

### ISSUE THREAD

**Issue by vovkav** [budowski/budoist#6]
plz, provide an .apk for those, that do not have google play market

**Comment by budowski** [comment]
Done - you can download it from the project's Git (at the root directory - "Budoist-release.apk").

**Comment by vovkav** [comment]
perhaps, a better way would be to realease it via 'downloads'

Also it would be good for a large noticable link to the .apk from readme

**Comment by budowski** [comment]
Done - now available in the "Downloads" section
