### ISSUE TITLE
task due date/time displaying incorrectly

### ISSUE THREAD

**Issue by Niibori** [budowski/budoist#9]
If I enter a task in the app with a due date only, it's fine.  If I include a time with the due date, it displays incorrectly on both the phone app & the website.  

Example: if I create a task on the website and set it as due "today @ 1200", it displays on the app (in any list - today, a specific query, etc.) as being due "tomorrow @ 0100" (+13h), although it's correctly highlighted with green and listed with the other "today" tasks, and if I open it to edit the task the correct time info ("today @ 1200") is shown.  If I create a task on the phone app with a time as well as date, it either displays on the app the same way (+13h) or occasionally it displays with no due date/time at all, and I can't discern any pattern or reason for why it displays the time/date incorrectly or not at all in this case.

The same task (set for "today @ 1200" and created via the app) is displaying as "yesterday @ 2300" (-13h) on the website, and highlighted/grouped with the overdue tasks from yesterday.  Editing the task, the time/date info is shown incorrectly as "yesterday @ 2300", the same as what's being displayed.

I've checked the basics I can think of - phone's date/time is set correctly, for example - but I don't know anyone else who uses the app so I'm not sure if it's just me or if others are having the same issue.

**Comment by budowski** [comment]
Hi,

Sorry for not responding earlier - had a couple of busy weeks - have you checked the timezone settings of the _app_ (not just the phone)?

**Comment by Niibori** [comment]
No problem.  Forgive my blindness, but I can't see anywhere to change the
timezone settings on the _app_ itself - just the format (1:00 PM vs.
13:00).  I'll be happy to check, though, if you can point me to the
settings for the timezone?

Thanks-
- Meira

**Comment by budowski** [comment]
You can go to the Todoist website -> Preferences -> Time Zone.
I'll leave this ticket open since you cannot currently change this option via Budoist (only via the website) - Hopefully, I'll add it in the next version.

**Comment by budowski** [comment]
Added timezone-changing support in 1.3.0
